import { File, Text } from "@asyncapi/generator-react-sdk";
import { emitDart } from "../src/emit-dart.js";
import { emitSwift } from "../src/emit-swift.js";
import { buildIR } from "../src/ir.js";
import { snakeCase } from "../src/names.js";

export default function Template({ asyncapi, params }) {
  const language = String(params.language).toLowerCase();
  const ir = buildIR(asyncapi, { moduleName: params.moduleName });
  if (language === "swift") {
    return (
      <File name={`Sources/${ir.moduleName}/AsyncAPIGenerated.swift`}>
        <Text>{emitSwift(ir)}</Text>
      </File>
    );
  }
  if (language === "dart") {
    const libraryName = snakeCase(params.moduleName);
    return [
      <File key="implementation" name="lib/src/asyncapi_generated.dart">
        <Text>{emitDart(ir)}</Text>
      </File>,
      <File key="library" name={`lib/${libraryName}.dart`}>
        <Text>{`// Generated by @soenan/asyncapi-generator. Do not edit.\nexport 'src/asyncapi_generated.dart';\n`}</Text>
      </File>
    ];
  }
  throw new Error(`Unsupported language ${JSON.stringify(params.language)}; expected swift or dart.`);
}
